#line 2 "src/lex.yy.c"

#line 4 "src/lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 101
#define YY_END_OF_BUFFER 102
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[277] =
    {   0,
        0,    0,  102,  101,   99,  100,   64,   96,   94,   66,
       59,   97,   51,   52,   60,   61,   93,   62,   55,   65,
       40,   40,   81,   80,   71,   82,   72,   79,   48,   48,
       48,   49,   50,   75,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       53,   76,   54,   63,   99,   74,    0,   45,    0,   95,
       85,   77,   90,    0,    0,   83,   57,    0,   40,   40,
       86,   58,   87,   56,   41,    0,   43,   84,   39,    0,
        0,   67,   69,   73,   70,   68,   48,   48,   48,   91,
       48,   48,   48,   48,   48,   48,   48,   48,   22,   48,

       48,   48,   48,   48,   48,   17,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   92,
       78,    0,   44,    0,    0,    0,    0,   47,    0,   43,
        0,   41,   42,   88,   89,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       20,   48,    1,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
        0,   98,    0,    0,   41,   46,   48,   38,   15,    7,
       48,   31,    3,   48,   48,   48,   48,   48,   18,   27,
       48,   48,   23,    5,   48,   48,   48,   48,   48,   48,

       48,   48,   48,   48,   48,   48,   48,   29,   48,   48,
        0,    0,   24,   33,   10,   48,   48,   48,   48,    4,
       48,   48,   48,   48,   48,    6,   48,   48,   48,   48,
       48,   28,   48,   48,   21,    0,    0,   48,   48,    2,
       13,   48,   48,   34,   48,   32,    8,   11,   26,   19,
       48,   48,   48,    0,    0,   48,   30,   35,   48,   48,
       16,   48,   48,    0,   25,   48,   14,    9,   12,    0,
       36,    0,    0,    0,   37,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   29,   29,   30,   29,
       31,   31,   32,   31,   31,   33,   34,   35,   31,   31,
       31,   31,   31,   36,   37,   31,   31,   38,   31,   31,
       39,   40,   41,   42,   43,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   31,   53,   54,   55,   56,
       57,   58,   31,   59,   60,   61,   62,   63,   64,   65,
       66,   31,   67,   68,   69,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[71] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    6,
        6,    1,    1,    1,    1,    1,    1,    6,    6,    6,
        7,    7,    7,    7,    7,    7,    7,    7,    1,    8,
        1,    1,    7,    5,    5,    6,    6,    6,    5,    7,
        7,    7,    7,    7,    7,    9,    7,    7,    9,    7,
        9,    7,    9,    7,    7,    7,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[288] =
    {   0,
        0,    0,  440,  441,  437,  441,  413,   66,  431,  411,
       63,  395,  441,  441,  409,   59,  441,   66,   74,   83,
       83,   90,  441,  441,   50,  408,   64,  441,    0,  397,
      394,  441,  441,  405,  367,   40,   61,   66,   63,   68,
      371,   77,  370,   65,  378,   78,  359,  368,  366,  371,
      441,   73,  441,  441,  419,  441,   76,  441,    0,  441,
      441,  441,  441,  410,  144,  441,  441,  115,  126,  138,
      441,  441,  441,  441,  131,  157,    0,  441,  161,  176,
        0,  394,  441,  441,  441,  393,    0,  381,  383,  441,
      354,  357,  365,  352,  367,  366,  353,  359,  345,  346,

      343,  343,  346,  343,  340,    0,  339,  343,   80,  353,
      112,  340,  346,  128,  343,  336,  115,  117,  341,  441,
      441,  382,  441,  381,  143,  192,  191,  207,  203,    0,
      198,  203,    0,  441,  441,  347,  356,  331,  333,  342,
      337,  325,  323,  105,  338,  336,  332,  324,  330,  333,
        0,  319,    0,  325,  311,  312,  318,  319,  308,  310,
      312,  306,  304,  304,  316,  306,  310,  314,  316,  305,
      348,  441,    0,  206,  209,  441,  346,    0,    0,    0,
      303,    0,    0,  295,  293,  301,  290,  297,    0,    0,
      291,  288,    0,    0,  304,  299,  294,  285,  285,  282,

      294,  289,  294,  293,  291,  281,  286,    0,  274,  286,
      175,  299,    0,    0,    0,  276,  277,  282,  273,    0,
      267,  281,  280,  264,  268,    0,  276,  276,  260,  269,
      271,    0,  262,  265,    0,    0,  288,  251,  251,    0,
        0,  258,  244,    0,  252,    0,    0,    0,    0,    0,
      245,  235,  208,  191,  218,  205,    0,    0,  196,  183,
        0,  186,  154,  131,    0,  130,    0,    0,    0,  142,
        0,  112,  105,   65,  441,  441,  231,  240,  245,  254,
      263,  272,  281,  286,  292,  299,  306
    } ;

static const flex_int16_t yy_def[288] =
    {   0,
      276,    1,  276,  276,  276,  276,  276,  277,  276,  276,
      276,  278,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  279,  279,
      279,  276,  276,  276,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      276,  276,  276,  276,  276,  276,  277,  276,  277,  276,
      276,  276,  276,  280,  281,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  282,  283,  276,  276,  276,
      284,  276,  276,  276,  276,  276,  279,  279,  279,  276,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,

      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  276,
      276,  285,  276,  276,  276,  276,  282,  282,  282,  283,
      276,  276,  284,  276,  276,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      285,  276,  286,  276,  276,  276,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,

      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      276,  276,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  287,  276,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  276,  276,  279,  279,  279,  279,  279,
      279,  279,  279,  276,  279,  279,  279,  279,  279,  276,
      279,  276,  276,  276,  276,    0,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276
    } ;

static const flex_int16_t yy_nxt[512] =
    {   0,
        4,    5,    6,    7,    8,    9,    4,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   23,   24,   25,   26,   27,   28,   29,   29,   29,
       29,   30,   29,   29,   31,   29,   29,   29,   32,    4,
       33,   34,   29,   35,   36,   37,   38,   39,   40,   41,
       29,   42,   29,   43,   29,   29,   29,   44,   45,   46,
       47,   48,   49,   50,   29,   29,   51,   52,   53,   54,
       58,   62,   67,   82,   83,   68,  275,   69,   70,   70,
       58,   72,   68,   71,   69,   70,   70,   63,   85,   86,
       73,   74,   75,   75,   75,   76,   92,  120,   93,   68,

       77,   79,   79,   70,   94,   59,   68,   78,   70,   70,
       70,   95,   80,   98,   96,   59,  100,   97,  101,   80,
       81,  103,   99,  109,  104,  106,  110,  102,  112,  113,
       80,  155,  107,   75,   75,   75,  156,   80,  114,  274,
      121,  115,   68,  273,   79,   79,   70,   81,  125,   75,
       75,   75,  123,  125,   68,   80,   70,   70,   70,  128,
      126,  158,  125,  128,  185,  186,  166,   80,  168,  129,
      169,  162,  159,   80,  167,  272,  271,   68,  126,   79,
       79,   70,  173,  125,  172,   80,  163,  125,  125,  131,
       80,  131,  125,  128,  132,  132,  132,  128,  270,  125,

      172,  269,  125,  129,  125,  174,  125,  174,   80,  128,
      175,  175,  175,  128,  236,  129,  132,  132,  132,  129,
      176,  132,  132,  132,  175,  175,  175,  175,  175,  175,
      236,   57,  268,   57,   57,   57,   57,   57,   57,   57,
       64,  267,   64,  266,   64,   64,   64,   64,   64,   87,
       87,   87,  265,   87,  122,  264,  122,  122,  122,  122,
      122,  263,  122,  124,  124,  124,  124,  124,  124,  124,
      124,  124,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  130,  262,  130,  130,  130,  130,  130,  130,  130,
      133,  133,  171,  261,  171,  171,  171,  171,  171,  260,

      171,  211,  211,  211,  259,  258,  211,  211,  254,  254,
      254,  257,  256,  254,  254,  255,  253,  252,  251,  250,
      249,  248,  247,  246,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  235,  234,  233,  232,  231,  230,  229,
      228,  227,  226,  225,  224,  223,  222,  221,  220,  219,
      218,  217,  216,  215,  214,  213,  212,  172,  210,  209,
      208,  207,  206,  205,  204,  203,  202,  201,  200,  199,
      198,  197,  196,  195,  194,  193,  192,  191,  190,  189,
      188,  187,  184,  183,  182,  181,  180,  179,  178,  177,
      172,  172,  170,  165,  164,  161,  160,  157,  154,  153,

      152,  151,  150,  149,  148,  147,  146,  145,  144,  143,
      142,  141,  140,  139,  138,  137,  136,  135,  134,  123,
       55,  119,  118,  117,  116,  111,  108,  105,   91,   90,
       89,   88,   84,   66,   65,   61,   60,   56,   55,  276,
        3,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,

      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276
    } ;

static const flex_int16_t yy_chk[512] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        8,   11,   16,   25,   25,   16,  274,   16,   16,   16,
       57,   18,   18,   16,   18,   18,   18,   11,   27,   27,
       18,   18,   19,   19,   19,   20,   36,   52,   36,   21,

       20,   21,   21,   21,   37,    8,   22,   20,   22,   22,
       22,   37,   21,   38,   37,   57,   39,   37,   39,   22,
       21,   40,   38,   44,   40,   42,   44,   39,   46,   46,
       21,  109,   42,   68,   68,   68,  109,   22,   46,  273,
       52,   46,   69,  272,   69,   69,   69,   21,   65,   75,
       75,   75,  125,   65,   70,   69,   70,   70,   70,   76,
       75,  111,   65,   76,  144,  144,  117,   70,  118,   76,
      118,  114,  111,   69,  117,  270,  266,   79,   75,   79,
       79,   79,  125,   65,  211,   70,  114,   65,   65,   80,
       79,   80,   65,  127,   80,   80,   80,  127,  264,   65,

      254,  263,   65,  127,   65,  126,   65,  126,   79,  128,
      126,  126,  126,  128,  211,  129,  131,  131,  131,  128,
      129,  132,  132,  132,  174,  174,  174,  175,  175,  175,
      254,  277,  262,  277,  277,  277,  277,  277,  277,  277,
      278,  260,  278,  259,  278,  278,  278,  278,  278,  279,
      279,  279,  256,  279,  280,  255,  280,  280,  280,  280,
      280,  253,  280,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  283,  252,  283,  283,  283,  283,  283,  283,  283,
      284,  284,  285,  251,  285,  285,  285,  285,  285,  245,

      285,  286,  286,  286,  243,  242,  286,  286,  287,  287,
      287,  239,  238,  287,  287,  237,  234,  233,  231,  230,
      229,  228,  227,  225,  224,  223,  222,  221,  219,  218,
      217,  216,  212,  210,  209,  207,  206,  205,  204,  203,
      202,  201,  200,  199,  198,  197,  196,  195,  192,  191,
      188,  187,  186,  185,  184,  181,  177,  171,  170,  169,
      168,  167,  166,  165,  164,  163,  162,  161,  160,  159,
      158,  157,  156,  155,  154,  152,  150,  149,  148,  147,
      146,  145,  143,  142,  141,  140,  139,  138,  137,  136,
      124,  122,  119,  116,  115,  113,  112,  110,  108,  107,

      105,  104,  103,  102,  101,  100,   99,   98,   97,   96,
       95,   94,   93,   92,   91,   89,   88,   86,   82,   64,
       55,   50,   49,   48,   47,   45,   43,   41,   35,   34,
       31,   30,   26,   15,   12,   10,    9,    7,    5,    3,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,

      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/lexer.l"
#line 3 "src/lexer.l"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>

#define MAX_SYMBOLS 20000
#define MAX_ERRORS 1000
int line_no = 1;

typedef struct{
    char* lexeme;
    char* token;
    int line_num;
}SYMTAB;

SYMTAB Symboltable[MAX_SYMBOLS];
int symcount = 0;

typedef struct{
    char* message;
    char* token;
    int line_num;
}Error;

Error error_list[MAX_ERRORS];
int error_count = 0;

/* Function to add an error to the error list */
void add_error(const char* msg, const char* token, int line_no) {
    if (error_count < MAX_ERRORS) {
        error_list[error_count].message = strdup(msg);
        error_list[error_count].token = strdup(token);
        error_list[error_count].line_num = line_no;
        error_count++;
    } else {
        printf("Error list is full. Cannot add more errors.\n");
    }
}

/* Function to print all errors in a structured format */
void print_errors() {
    printf("\n==================================================================================================================\n");
    printf("                                              ERROR REPORT\n");
    printf("==================================================================================================================\n");
    printf("| %-5s | %-40s | %-40s | %-15s |\n", "ID", "Description", "Token", "Line Number");
    printf("------------------------------------------------------------------------------------------------------------------\n");

    for (int i = 0; i < error_count; i++) {
        printf("| %-5d | %-40s | %-40s | %-15d |\n", 
               i + 1, 
               error_list[i].message, 
               error_list[i].token, 
               error_list[i].line_num);
    }

    printf("==================================================================================================================\n");
}

void addtosymtab(const char* lex, const char* tok, int line_no){
    if(symcount >= MAX_SYMBOLS){
        add_error("full symbol table", lex, line_no);
    return;
    }
    Symboltable[symcount].lexeme = strdup(lex);
    Symboltable[symcount].token = strdup(tok);
    Symboltable[symcount].line_num = line_no;

    if(strcmp(Symboltable[symcount].lexeme,lex) != 0 || strcmp(Symboltable[symcount].token,tok) != 0){
        add_error("allocation failure", lex, line_no);
        return;
    }
    symcount++;
}

void print_symtab() {
    printf("\n=========================================================================================================\n");
    printf("|                                            SYMBOL TABLE                                               |\n");
    printf("=========================================================================================================\n");
    printf("| %-40s | %-40s | %-15s |\n", "LEXEME", "TOKEN", "LINE");
    printf("---------------------------------------------------------------------------------------------------------\n");

    for (int i = 0; i < symcount; i++) {
        printf("| %-40s | %-40s | %-15d |\n", 
               Symboltable[i].lexeme, 
               Symboltable[i].token, 
               Symboltable[i].line_num);
    }

    printf("=========================================================================================================\n");
}



#line 747 "src/lex.yy.c"
/* Define keyword tokens */
/*regex for literals*/
/* Define punctuation macros */
#line 751 "src/lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 202 "src/lexer.l"

#line 970 "src/lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 277 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 441 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 203 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 204 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 205 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 206 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 207 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 208 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 209 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 211 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 212 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 213 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 214 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 215 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 216 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 217 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 218 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 219 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 221 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 222 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 223 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 225 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 226 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 227 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 229 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 230 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 231 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 233 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 234 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 235 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 237 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 238 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 240 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 242 "src/lexer.l"
{ addtosymtab("RETURN", "Keyword", line_no); }  // Explicitly display RETURN instead of yytext
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 244 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 245 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 246 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 247 "src/lexer.l"
{ addtosymtab(yytext, "Keyword", line_no); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 249 "src/lexer.l"
{ addtosymtab(yytext, "CONST_INT", line_no); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 250 "src/lexer.l"
{ addtosymtab(yytext, "CONST_NULL", line_no); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 251 "src/lexer.l"
{ addtosymtab(yytext, "OCTAL_CONST", line_no); } /* put octal rule above int to prioritise leading 0's*/
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 252 "src/lexer.l"
{ addtosymtab(yytext, "INTEGER", line_no); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 253 "src/lexer.l"
{ addtosymtab(yytext, "FLOAT", line_no); } /*also matches 1e3 as float which is intended (without decimal) */
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 254 "src/lexer.l"
{ addtosymtab(yytext, "HEX_CONST", line_no); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 255 "src/lexer.l"
{} /*do nothing*/
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 256 "src/lexer.l"
{ addtosymtab(yytext, "CHARACTER CONSTANT", line_no); } /*contains any char except \ , if there is \, then there must be another character behind it. */
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 257 "src/lexer.l"
{ addtosymtab(yytext, "STRING LITERAL", line_no); } /*allows all characters, no escape sequences defined*/
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 258 "src/lexer.l"
{ 
    for (int i = 0; yytext[i] != '\0'; i++) {
        if (yytext[i] == '\n') {
            line_no++;  // Increment line number for each newline in the multi-line comment
        }
    }
}
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 266 "src/lexer.l"
{
    for (int i = 0; yytext[i] != '\0'; i++) {
        if (yytext[i] == '\n') {
            line_no++;  // Increment line number for each newline in the unterminated multi-line comment
        }
    }
    add_error("Error: Unterminated Multiline Comment", yytext, line_no);
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 278 "src/lexer.l"
{addtosymtab(yytext, "ID", line_no);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 280 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_LEFT_SQ_BRACKET", line_no); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 281 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_RIGHT_SQ_BRACKET", line_no); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 282 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_LEFT_BRACKET", line_no); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 283 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_RIGHT_BRACKET", line_no); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 284 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_LEFT_CURLY_BRACKET", line_no); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 285 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_RIGHT_CURLY_BRACKET", line_no); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 286 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_DOT", line_no); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 287 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_ARROW", line_no); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 288 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_INCREMENT", line_no); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 289 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_DECREMENT", line_no); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 290 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_BITWISE_AND", line_no); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 291 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_STAR", line_no); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 292 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_PLUS", line_no); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 293 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_MINUS", line_no); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 294 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_BITWISE_NOT", line_no); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 295 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_NOT", line_no); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 296 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_SLASH", line_no); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 297 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_MOD", line_no); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 298 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_LSHIFT", line_no); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 299 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_RSHIFT", line_no); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 300 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_LESS_THAN_OR_EQUAL", line_no); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 301 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_GREATER_THAN_OR_EQUAL", line_no); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 302 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_LESS_THAN", line_no); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 303 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_GREATER_THAN", line_no); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 304 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_EQUALS", line_no); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 305 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_NOT_EQUAL", line_no); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 306 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_BITWISE_XOR", line_no); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 307 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_BITWISE_OR", line_no); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 308 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_AND", line_no); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 309 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_OR", line_no); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 310 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_TERNARY", line_no); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 311 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_SEMICOLON", line_no); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 312 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_COLON", line_no); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 313 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_ASSIGN", line_no); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 314 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_MULT_ASSIGN", line_no); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 315 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_SLASH_ASSIGN", line_no); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 316 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_MOD_ASSIGN", line_no); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 317 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_PLUS_ASSIGN", line_no); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 318 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_MINUS_ASSIGN", line_no); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 319 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_LSHIFT_ASSIGN", line_no); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 320 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_RSHIFT_ASSIGN", line_no); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 321 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_AND_ASSIGN", line_no); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 322 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_XOR_ASSIGN", line_no); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 323 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_OR_ASSIGN", line_no); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 324 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_COMMA", line_no); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 325 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_PREPROCESSOR_TOKEN", line_no); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 326 "src/lexer.l"
{ addtosymtab(yytext, "PUNC_DOUBLE_HASH", line_no); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 328 "src/lexer.l"
{ add_error("Error: Missing Terminal \" ", yytext, line_no); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 329 "src/lexer.l"
{ add_error("Error: Missing Terminal \' ", yytext, line_no); }
	YY_BREAK
case 98:
/* rule 98 can match eol */
YY_RULE_SETUP
#line 330 "src/lexer.l"
{ 
    add_error("Error: Invalid char constant", yytext, line_no);
}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 334 "src/lexer.l"
{ /* Ignore whitespaces */ }
	YY_BREAK
case 100:
/* rule 100 can match eol */
YY_RULE_SETUP
#line 335 "src/lexer.l"
{line_no++;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 336 "src/lexer.l"
ECHO;
	YY_BREAK
#line 1551 "src/lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 277 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 277 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 276);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 336 "src/lexer.l"

main(int argc, char **argv)
{
yylex();
if(error_count == 0)print_symtab();
else print_errors();
return 0;
}
 
